# Filters used by [dorny/path-filters](https://github.com/dorny/paths-filter)
# to detect changes in each subproject, and only run the corresponding jobs.

rust: &rust
  - "src/**"
  - "Cargo.toml"
  - "Cargo.lock"
  - ".github/workflows/ci.yml"
